In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("IBM HR Employee Attrition Data.csv", encoding='unicode_escape')
df

,ï»¿Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [3]:
df = df.rename(columns = {"ï»¿Age": "Age"})

In [4]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
df.shape

(1470, 35)

In [7]:
df.describe().round(2)

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.00,1470.00,1470.00,1470.00,1470.0,1470.00,1470.00,1470.00,1470.00,1470.00,...,1470.00,1470.0,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00
mean,36.92,802.49,9.19,2.91,1.0,1024.87,2.72,65.89,2.73,2.06,...,2.71,80.0,0.79,11.28,2.80,2.76,7.01,4.23,2.19,4.12
std,9.14,403.51,8.11,1.02,0.0,602.02,1.09,20.33,0.71,1.11,...,1.08,0.0,0.85,7.78,1.29,0.71,6.13,3.62,3.22,3.57
min,18.00,102.00,1.00,1.00,1.0,1.00,1.00,30.00,1.00,1.00,...,1.00,80.0,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
25%,30.00,465.00,2.00,2.00,1.0,491.25,2.00,48.00,2.00,1.00,...,2.00,80.0,0.00,6.00,2.00,2.00,3.00,2.00,0.00,2.00
50%,36.00,802.00,7.00,3.00,1.0,1020.50,3.00,66.00,3.00,2.00,...,3.00,80.0,1.00,10.00,3.00,3.00,5.00,3.00,1.00,3.00
75%,43.00,1157.00,14.00,4.00,1.0,1555.75,4.00,83.75,3.00,3.00,...,4.00,80.0,1.00,15.00,3.00,3.00,9.00,7.00,3.00,7.00
max,60.00,1499.00,29.00,5.00,1.0,2068.00,4.00,100.00,4.00,5.00,...,4.00,80.0,3.00,40.00,6.00,4.00,40.00,18.00,15.00,17.00

In [8]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

## [IBM HR Employee Attrition EDA Report](https://github.com/nibeditans/Employee-Attrition-Analysis-On-IBM-HR-Data/blob/main/IBM_HR_EDA_Report.html)

<b style="color:purple;">Drop the constant columns from the dataset.</b>

In [ ]:
df = df.drop(columns=["EmployeeCount", "Over18", "StandardHours"])

:

In [ ]:
df.shape

<h2 style="color:green;">Correlation Heatmap - Relationships b/w Features</h2>

<b style="color:purple;">Numeric Columns</b>

In [ ]:
numeric_df = df.select_dtypes(include=["int", "float"])
numeric_df.columns

<b style="color:purple;">Categorical Columns</b>

In [ ]:
df.select_dtypes(exclude=["int", "float"]).columns

<b style="color:purple;">Correlation Matrix Heatmap</b>

In [ ]:
corr_matrix = numeric_df.corr()
corr_matrix

In [ ]:
plt.figure(figsize = (20, 6))
sns.heatmap(data = corr_matrix, annot = True, cmap = "gist_rainbow", fmt = ".2f")
plt.title("Correlation Matrix - Relationships b/w Features")
plt.show()

<h2 style="color:green;">Histograms for the columns with a significant number of Zeros</h2>

<b style="color:green; background-color:yellow">Number of Companies Worked</b>

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["NumCompaniesWorked"], bins = 10, edgecolor = "w", color = "g")
plt.title("Number of Companies Worked at")
plt.show()

<b style="color:green; background-color:yellow">Last Year Training Times</b>

In [ ]:
plt.figure(figsize = (8, 4))
sns.histplot(df["TrainingTimesLastYear"], bins = 10, 
             color = "#93ff05", kde = True) # kde=True adds a kernel density estimate
plt.title("Last Year Training Times")
plt.show()

<b style="color:green; background-color:yellow">Number of Years at Company</b>

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["YearsAtCompany"], bins = 10, edgecolor = "w", color = "m")
plt.title("Number of Years at Company")
plt.show()

<b style="color:green; background-color:yellow">Years in Current Role</b>

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["YearsInCurrentRole"], bins = 10, edgecolor = "w", color = "c")
plt.title("Years in Current Role")
plt.show()

<b style="color:green; background-color:yellow">Number of Years since Last Promotion</b>

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["YearsSinceLastPromotion"], bins = 10, edgecolor = "w", color = "y")
plt.title("Number of Years since Last Promotion")
plt.show()

<b style="color:green; background-color:yellow">Years with Current Manager</b>

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["YearsWithCurrManager"], bins = 10, edgecolor = "w", color = "r")
plt.title("Years with Current Manager")
plt.show()

____________________
____________________
____________________
____________________

<h2 style="color:green;">EDA</h2>

<b style="color:purple;">Display the first 5 rows of the dataset.</b>

In [ ]:
df.head()

<b style="color:purple;">Check the number of rows and columns.</b>

In [ ]:
df.shape

<b style="color:purple;">Get summary statistics for numerical columns.</b>

In [ ]:
df.describe().round(2)

<b style="color:purple;">Identify any missing values in the dataset.</b>

In [ ]:
df.isnull().sum()

<b style="color:purple;">Check for duplicate records.</b>

In [ ]:
df[df.duplicated()]

<h3 style="color:blue;">Data Type Analysis</h3>

<b style="color:purple;">Display the data types of each column.</b>

In [ ]:
df.dtypes

<b style="color:purple;">Identify categorical and numerical columns separately.</b>

In [ ]:
df.select_dtypes(include=["int", "float"]).columns

In [ ]:
df.select_dtypes(exclude=["int", "float"]).columns

<h3 style="color:blue;">Univariate Analysis</h3>

<b style="color:purple;">Plot the distribution of 
    <b style="color:green; background-color:yellow">Age</b>, 
    <b style="color:green; background-color:yellow">Monthly Income</b>, and 
    <b style="color:green; background-color:yellow">Total Working Years</b> using histograms.</b>

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["Age"], bins = 10, edgecolor = "w", color = "g")
plt.title("Age Distribution")
plt.show()

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["MonthlyIncome"], bins = 10, edgecolor = "w", color = "y")
plt.title("Monthly Income Distribution")
plt.show()

In [ ]:
plt.figure(figsize = (8, 4))
plt.hist(df["TotalWorkingYears"], bins = 10, edgecolor = "w", color = "m")
plt.title("Total Working Years Distribution")
plt.show()

<b style="color:purple;">Analyze the frequency of categorical columns: 
    <b style="color:green; background-color:yellow">Job Role</b>, 
    <b style="color:green; background-color:yellow">Department</b>, and 
    <b style="color:green; background-color:yellow">Education Field</b> using bar charts.</b>

In [ ]:
plt.figure(figsize = (8, 4))
sns.countplot(x = df["JobRole"], color = "g")
plt.title("Job Role Distribution")
plt.xticks(rotation = 40)
plt.show()

In [ ]:
plt.figure(figsize = (8, 4))
sns.countplot(x = df["Department"], color = "y")
plt.title("Department Distribution")
plt.show()

In [ ]:
plt.figure(figsize = (8, 4))
sns.countplot(x = df["EducationField"], color = "m")
plt.title("Education Field Distribution")
plt.xticks(rotation = 40)
plt.show()

<h3 style="color:blue;">Attrition Analysis</h3>

<b style="color:purple;">Find the percentage of employees who have left 
    <b style="color:green; background-color:yellow">(Attrition = "Yes")</b> vs. those who stayed
    <b style="color:green; background-color:yellow">(Attrition = "No")</b>.</b>

In [ ]:
left_count = df["Attrition"].value_counts()["Yes"]
stayed_count = df["Attrition"].value_counts()["No"]
total_emps = df.shape[0]

In [ ]:
left_per = round((left_count / total_emps) * 100, 2)
left_per

In [ ]:
stayed_per = round((stayed_count / total_emps) * 100, 2)
stayed_per

<b style="color:purple;">Create a count plot to visualize the Attrition distribution.</b>

In [ ]:
plt.figure(figsize = (8, 4))
sns.countplot(x = df["Attrition"], color = "g")
plt.title("Attrition Distribution")
plt.show()

<b style="color:purple;">Compare Average 
    <b style="color:green; background-color:yellow">Monthly Income</b> of employees who left vs. those who stayed.</b>

In [ ]:
left_df = df[df['Attrition'] == 'Yes']
stayed_df = df[df['Attrition'] == 'No']

In [ ]:
avg_income_left = left_df['MonthlyIncome'].mean().round(2)
avg_income_stayed = stayed_df['MonthlyIncome'].mean().round(2)

In [ ]:
avg_income_left

In [ ]:
avg_income_stayed

In [ ]:
income_diff = avg_income_stayed - avg_income_left
income_diff.round(2)

<h2 style="color:green;">Bivariate Analysis & Feature Relationships</h2>

<h3 style="color:blue;">Correlation Analysis</h3>

<b style="color:purple;">Compute the correlation matrix for all numerical features.</b>

In [ ]:
corr_matrix = df.select_dtypes(include=["int", "float"]).corr()
corr_matrix

<b style="color:purple;">Visualize the heatmap of correlations.</b>

In [ ]:
plt.figure(figsize = (20, 6))
sns.heatmap(data = corr_matrix, annot = True, cmap = "Greens", fmt = ".2f")
plt.title("Correlation Matrix - Relationships b/w Features")
plt.show()

<div style="border:2px solid black;  
            background-color:yellow; 
            color:green;
            font-weight:bold;
            white-space:pre; 
            max-width:400px; 
            line-height:0.5">
    <ul>
        <li>JobLevel and MonthlyIncome: <b style="color:red;">0.95</b></li>
        <li>TotalWorkingYears and MonthlyIncome: <b style="color:red;">0.78</b></li>
        <li>YearsAtCompany and YearsInCurrentRole: <b style="color:red;">0.76</b></li>
        <li>YearsWithCurrManager and YearsInCurrentRole: <b style="color:red;">0.77</b></li>
        <li>TotalWorkingYears and YearsAtCompany: <b style="color:red;">0.63</b></li>
    </ul>
</div>

<p style="color:purple;">The strong positive correlations suggest relationships tied to career progression, such as higher 
    <b style="color:green; background-color:yellow">job levels</b>, 
    <b style="color:green; background-color:yellow">longer tenure</b>, and 
    <b style="color:green; background-color:yellow">increased income</b>. Weak or negligible correlations indicate that certain features may not significantly impact other variables in this dataset. From this insights, we could do further analysis, such as identifying factors influencing employee satisfaction or retention.</p>

<h3 style="color:blue;"> Attrition vs. Numeric Features</h3>

<b style="color:purple;">Compare 
    <b style="color:green; background-color:yellow">Monthly Income</b>, 
    <b style="color:green; background-color:yellow">Total Working Years</b>, and 
    <b style="color:green; background-color:yellow">Age</b> distributions for employees who left vs. stayed.</b>

In [ ]:
left_df

In [ ]:
stayed_df

In [ ]:
plt.figure(figsize = (20, 6))

# Monthly Income
plt.subplot(1, 3, 1)
plt.hist(left_df["MonthlyIncome"], bins = 20, alpha = 0.5, 
         color = "#004f15", label = "Left")
plt.hist(stayed_df["MonthlyIncome"], bins=20, alpha = 0.5, 
         color = "#e7f705", label = "Stayed")
plt.title("Monthly Income Distribution")
plt.legend()

# Total Working Years
plt.subplot(1, 3, 2)
plt.hist(left_df["TotalWorkingYears"], bins = 20, alpha = 0.5, 
         color = "#004f15", label = "Left")
plt.hist(stayed_df["TotalWorkingYears"], bins = 20, alpha = 0.5, 
         color = "#e7f705", label = "Stayed")
plt.title("Total Working Years Distribution")
plt.legend()

# Age
plt.subplot(1, 3, 3)
plt.hist(left_df["Age"], bins = 20, alpha = 0.5, 
         color = "#004f15", label = "Left")
plt.hist(stayed_df["Age"], bins = 20, alpha = 0.5, 
         color = "#e7f705", label = "Stayed")
plt.title("Age Distribution")
plt.legend()

plt.show()

<div style="border:2px solid black; 
            padding:5px;
            color:purple;
            max-width:600px; 
            line-height:1.5;
            word-wrap: break-word;">
    <ul>
        <li><b style="color:green;">Monthly Income</b>: Employees who left seem to have lower income distributions compared to those who stayed.</li>
        <li><b style="color:green;">Total Working Years</b>: Employees with fewer working years seem more likely to leave.</li>
        <li><b style="color:green;">Age</b>: Younger employees have higher attrition, while older employees tend to stay.</li>
    </ul>
</div>

<b style="color:purple;">Use violin plots or box plots for better visualization.</b>

In [ ]:
plt.figure(figsize = (20, 6))

# Monthly Income
plt.subplot(1, 3, 1)
sns.violinplot(data = df, x = "Attrition", y = "MonthlyIncome", 
               hue = "Attrition", palette = ["#ecfc05", "#0df505"])
plt.title("Monthly Income Distribution")

# Total Working Years
plt.subplot(1, 3, 2)
sns.violinplot(data = df, x = "Attrition", y = "TotalWorkingYears", 
               hue = "Attrition", palette = ["#ecfc05", "#0df505"])
plt.title("Total Working Years Distribution")

# Age
plt.subplot(1, 3, 3)
sns.violinplot(data = df, x = "Attrition", y = "Age", 
               hue = "Attrition", palette = ["#ecfc05", "#0df505"])
plt.title("Age Distribution")

plt.show()

<div style="border:2px solid black; 
            padding:5px;
            color:purple;
            max-width:600px; 
            line-height:1.5;
            word-wrap: break-word;">
    <ul>
        <li><b style="color:green;">Monthly Income</b>: Clear gap in distribution—lower-income employees are more likely to leave.</li>
        <li><b style="color:green;">Total Working Years</b>: Employees with shorter careers show higher attrition, reinforcing the histogram trend.</li>
        <li><b style="color:green;">Age</b>: The younger demographic faces more attrition, possibly due to career shifts or better opportunities.</li>
    </ul>
</div>

<b style="border:4px solid green; 
          padding:5px;
          color:red;">Low salary, fewer years of experience, and younger age = Higher Attrition Risk</b>

<h3 style="color:blue;">Attrition vs. Categorical Features</h3>

<b style="color:purple;">Create count plots for categorical variables like 
    <b style="color:green; background-color:yellow">Job Role</b>, 
    <b style="color:green; background-color:yellow">Department</b>, 
    <b style="color:green; background-color:yellow">Education Field</b> segmented by 
    <b style="color:green; background-color:yellow">Attrition</b>.</b>

In [ ]:
plt.figure(figsize = (20, 6))

# Job Role
plt.subplot(1, 3, 1)
sns.countplot(data = df, x = "JobRole", 
               hue = "Attrition", palette = ["#ecfc05", "#0df505"])
plt.title("Job Role Distribution")
plt.xticks(rotation = 90)

# Department
plt.subplot(1, 3, 2)
sns.countplot(data = df, x = "Department", 
               hue = "Attrition", palette = ["#ecfc05", "#0df505"])
plt.title("Department Distribution")
plt.xticks(rotation = 90)

# Education Field
plt.subplot(1, 3, 3)
sns.countplot(data = df, x = "EducationField", 
               hue = "Attrition", palette = ["#ecfc05", "#0df505"])
plt.title("Education Field Distribution")
plt.xticks(rotation = 90)

plt.show()

<b style="color:green; background-color:yellow">Job Role</b>

<div style="border:2px solid black; 
            padding:5px;
            color:purple;
            max-width:600px; 
            line-height:1.5;
            word-wrap: break-word;">
    <ul>
        <li>
            <b style="color:green;">Sales Executive and Research Scientist</b> roles have the highest counts of employees, but attrition is relatively higher in these roles compared to others.</li>
        <li>
            <b style="color:green;">Laboratory Technician</b> also shows a significant number of employees leaving, indicating potential dissatisfaction or challenges in this role.</li>
        <li>Roles like 
            <b style="color:green;">Manager, Research Director, and Healthcare Representative</b> have lower attrition rates, suggesting better retention in these positions.</li>
    </ul>
</div>

<b style="color:green; background-color:yellow">Department</b>

<div style="border:2px solid black; 
            padding:5px;
            color:purple;
            max-width:600px; 
            line-height:1.5;
            word-wrap: break-word;">
    <ul>
        <li>The 
            <b style="color:green;">Research & Development</b> department has the largest workforce, but it also experiences substantial attrition, although the majority of employees stay.</li>
        <li>The 
            <b style="color:green;">Sales </b> department shows a relatively higher proportion of attrition compared to its total workforce.</li>
        <li>The 
            <b style="color:green;">Human Resources</b> department has the smallest workforce and exhibits minimal attrition.</li>
    </ul>
</div>

<b style="color:green; background-color:yellow">Education Field</b>

<div style="border:2px solid black; 
            padding:5px;
            color:purple;
            max-width:600px; 
            line-height:1.5;
            word-wrap: break-word;">
    <ul>
        <li>Employees with a background in 
            <b style="color:green;">Life Sciences and Medical</b> fields dominate the workforce. However, attrition is more noticeable in these fields, particularly in 
            <b style="color:green;">Life Sciences</b>.</li>
        <li>Fields like 
            <b style="color:green;">Marketing, Technical Degree, and Human Resources</b> exhibit lower attrition rates, possibly indicating better alignment with job roles or satisfaction levels.</li>
    </ul>
</div>

<b style="border:4px solid green; 
          padding:5px;
          color:red;">Retention efforts should focus on Sales, R&D, and employees from Medical/Life Sciences backgrounds.</b>